name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-20.04
    env:
      DISPLAY: :0

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y xvfb libxml2-utils qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev qt5-default qttools5-dev-tools
        # start xvfb in the background
        sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
        cur=`pwd`
        python -m pip install --upgrade pip
        pip install ".[dev]"

    - name: Run pre-commit checks
      run: |
        pre-commit run --all-files

    - name: Run tests
      run: |
        pytest tests/
